
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Win10
 */
public class firstscreen extends javax.swing.JFrame  {

    /**
     * Creates new form firstscreen
     */
    public firstscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        suru = new javax.swing.JPanel();
        sign2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        admintxt = new javax.swing.JTextField();
        adminpas = new javax.swing.JPasswordField();
        login2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        suruchi = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JPasswordField();
        log1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARY MANAGEMENT");
        setMaximumSize(new java.awt.Dimension(900, 905));
        setMinimumSize(new java.awt.Dimension(900, 905));
        setPreferredSize(new java.awt.Dimension(900, 905));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(880, 767));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        pane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        pane3.setMaximumSize(new java.awt.Dimension(1000, 900));
        pane3.setMinimumSize(new java.awt.Dimension(1000, 900));
        pane3.setPreferredSize(new java.awt.Dimension(1000, 900));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(970, 810));
        jPanel11.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Visit Library Management");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(20, 230, 740, 60);

        jLabel7.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hurry Up!!!!!");
        jPanel11.add(jLabel7);
        jLabel7.setBounds(290, 330, 230, 50);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel14.setText("Here, users can view, issue ,view issued books and return books");
        jPanel11.add(jLabel14);
        jLabel14.setBounds(60, 520, 650, 60);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel26.setText("Users can read any category of books like Magazines,newspaper etc.");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(50, 430, 690, 50);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel27.setText("To grab Library features Signup and then Login");
        jPanel11.add(jLabel27);
        jLabel27.setBounds(170, 600, 580, 60);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\siv.png")); // NOI18N
        jLabel28.setText(" ");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPanel11.add(jLabel28);
        jLabel28.setBounds(60, 60, 650, 110);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\Saved Pictures\\back2.jpg")); // NOI18N
        jLabel29.setText("jLabel25");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        jLabel29.setPreferredSize(new java.awt.Dimension(921, 756));
        jPanel11.add(jLabel29);
        jLabel29.setBounds(10, 0, 750, 780);

        pane3.addTab("welcome", jPanel11);

        suru.setBackground(new java.awt.Color(0, 0, 0));
        suru.setLayout(null);

        sign2.setBackground(new java.awt.Color(0, 0, 0));
        sign2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        sign2.setForeground(new java.awt.Color(255, 255, 255));
        sign2.setText("Signup");
        sign2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        sign2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign2ActionPerformed(evt);
            }
        });
        suru.add(sign2);
        sign2.setBounds(290, 550, 250, 80);

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\user.png")); // NOI18N
        suru.add(jLabel39);
        jLabel39.setBounds(270, 100, 200, 200);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Username");
        suru.add(jLabel40);
        jLabel40.setBounds(30, 350, 190, 50);

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Password");
        suru.add(jLabel41);
        jLabel41.setBounds(30, 460, 190, 60);

        t8.setEditable(false);
        t8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        suru.add(t8);
        t8.setBounds(220, 340, 390, 60);

        t9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        suru.add(t9);
        t9.setBounds(220, 460, 390, 60);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        suru.add(jButton7);
        jButton7.setBounds(290, 650, 250, 80);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\lib.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 5, true), "New account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 3, 24), new java.awt.Color(255, 51, 0))); // NOI18N
        suru.add(jLabel2);
        jLabel2.setBounds(10, 70, 750, 700);

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\Saved Pictures\\usera.jpg")); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        suru.add(jLabel33);
        jLabel33.setBounds(250, 110, 120, 140);

        jLabel43.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Create new account here!!!!");
        suru.add(jLabel43);
        jLabel43.setBounds(60, 20, 583, 48);

        pane3.addTab("new account", suru);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "ADMIN LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 3, 36), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 804));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\Saved Pictures\\admin1.png")); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USERNAME");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");

        admintxt.setText("jTextField1");
        admintxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admintxtActionPerformed(evt);
            }
        });

        adminpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasActionPerformed(evt);
            }
        });

        login2.setBackground(new java.awt.Color(0, 0, 204));
        login2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        login2.setForeground(new java.awt.Color(255, 255, 255));
        login2.setText("LOGIN");
        login2.setBorder(null);
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 204));
        jButton8.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Back");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(admintxt, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addComponent(adminpas))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(login2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminpas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(87, 87, 87)
                .addComponent(login2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pane3.addTab("admin login", jPanel3);

        suruchi.setBackground(new java.awt.Color(0, 0, 0));
        suruchi.setPreferredSize(new java.awt.Dimension(970, 810));
        suruchi.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 5));

        jLabel30.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Login with existing account!!!!");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel30)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        suruchi.add(jPanel15);
        jPanel15.setBounds(10, 0, 750, 70);

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\Saved Pictures\\usera.jpg")); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        suruchi.add(jLabel31);
        jLabel31.setBounds(90, 500, 120, 130);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel32.setText("Username");
        suruchi.add(jLabel32);
        jLabel32.setBounds(50, 250, 190, 50);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel34.setText("Password");
        suruchi.add(jLabel34);
        jLabel34.setBounds(50, 360, 170, 60);

        t6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 3, true));
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        suruchi.add(t6);
        t6.setBounds(220, 250, 530, 60);

        t7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 3, true));
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        suruchi.add(t7);
        t7.setBounds(220, 360, 530, 60);

        log1.setBackground(new java.awt.Color(0, 0, 0));
        log1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        log1.setForeground(new java.awt.Color(255, 255, 255));
        log1.setText("login");
        log1.setActionCommand("LOGIN");
        log1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log1ActionPerformed(evt);
            }
        });
        suruchi.add(log1);
        log1.setBounds(280, 490, 300, 70);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        suruchi.add(jButton6);
        jButton6.setBounds(280, 580, 300, 70);

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset password");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 3));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        suruchi.add(reset);
        reset.setBounds(150, 680, 570, 70);

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\men.jpg")); // NOI18N
        jLabel38.setText("jLabel2");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        suruchi.add(jLabel38);
        jLabel38.setBounds(10, 115, 750, 660);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New librarian!!!pls create acoount 1st ");
        suruchi.add(jLabel1);
        jLabel1.setBounds(20, 80, 510, 20);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("then login here.....");
        suruchi.add(jLabel3);
        jLabel3.setBounds(530, 80, 230, 20);

        pane3.addTab("librarian login", suruchi);

        jPanel1.add(pane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 821));
        pane3.getAccessibleContext().setAccessibleName("home");

        jPanel10.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Welcome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 800));

        b1.setBackground(new java.awt.Color(0, 0, 204));
        b1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("ADMIN LOGIN");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(0, 0, 204));
        b2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("LIBRARIAN LOGIN");
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 0, 204));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Signup");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1040, 864));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
pane3.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
pane3.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log1ActionPerformed
  String username=t6.getText();
       String password=t7.getText();
       
           if(username.trim().isEmpty()&& password.trim().isEmpty())
       {
                 JOptionPane.showMessageDialog(this, "Pls enter above field...");

       }
        else if(username.trim().isEmpty())
                {
                         JOptionPane.showMessageDialog(this, "Pls enter username...");
  
                }
        else if(password.trim().isEmpty())
        {
                JOptionPane.showMessageDialog(this, "pls enter password....");

        }      
       try
       {
       Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/management?zeroDateTimeBehavior=convertToNull","root","");
   Statement s=con.createStatement();
   ResultSet rs=s.executeQuery("select* from signup where username='"+username+"' and password='"+password+"'");

   if(rs.next())
   { 
       JOptionPane.showMessageDialog(this, "Sucessfully login");
     Loading Viewbooks=  new Loading ();
      Viewbooks.setUpLoading();

     Viewbooks.setVisible(true);
   
       this.dispose();
       
       
      
                 
     
   }
 
  
   else
   {
       JOptionPane.showMessageDialog(this, "Login failed....");
   }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e);
       }
}
       
                                       

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void signActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }//GEN-LAST:event_log1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    new library().setVisible(true); 
this.dispose();// 
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sign2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign2ActionPerformed


        String username=t8.getText();
       

        

        String password=t9.getText();
        if(username.trim().isEmpty()&& password.trim().isEmpty())
       {
                 JOptionPane.showMessageDialog(this, "Pls enter above field...");

       }
        else if(username.trim().isEmpty())
                {
                         JOptionPane.showMessageDialog(this, "Pls enter username...");
  
                }
        else if(password.trim().isEmpty())
        {
                JOptionPane.showMessageDialog(this, "pls enter password....");

        }  
        else{
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/management?zeroDateTimeBehavior=convertToNull","root","");
   
        PreparedStatement ps=(PreparedStatement) con.prepareStatement("insert into signup values(?,?)");
       if(username!=null&& password!=null)
       {
        ps.setString(1, username);
        ps.setString(2,password);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"sucessfull done");}
       else
       {
            JOptionPane.showMessageDialog(this,"Failed...");
       
       }
        
        
    }
    catch(Exception e)
    {
        System.out.println(e);
}  
        }// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_sign2ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
new library().setVisible(true); 
this.dispose();//         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
   password gf=new password(); 
gf.setVisible(true);
     gf.pack();
     gf.setLocationRelativeTo(null);
     gf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     this.dispose();            // TODO add your handling code here:
                  // TODO add your handling code here:
    }//GEN-LAST:event_resetMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pane3.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void admintxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admintxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admintxtActionPerformed

    private void adminpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpasActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
pane3.setSelectedIndex(3);                // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
String username=admintxt.getText();
       String password=adminpas.getText();
       
           if(username.trim().isEmpty()&& password.trim().isEmpty())
       {
                 JOptionPane.showMessageDialog(this, "Pls enter above field...");

       }
        else if(username.trim().isEmpty())
                {
                         JOptionPane.showMessageDialog(this, "Pls enter username...");
  
                }
        else if(password.trim().isEmpty())
        {
                JOptionPane.showMessageDialog(this, "pls enter password....");

        }      
       try
       {
       Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/management?zeroDateTimeBehavior=convertToNull","root","");
   Statement s=con.createStatement();
   ResultSet rs=s.executeQuery("select username,password from signup where username='"+username+"'");

   if(rs.next())
   { 
       if(password.equals(rs.getString("password")))
       { 
       JOptionPane.showMessageDialog(this, "Sucessfully login");
     adminloading Viewbooks=  new adminloading ();
      Viewbooks.setUpLoading();

     Viewbooks.setVisible(true);
   
       this.dispose();}
       
   }
    else
   {
       JOptionPane.showMessageDialog(this, "Login failed....");
   }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e);
       }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_login2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminpas;
    private javax.swing.JTextField admintxt;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton log1;
    private javax.swing.JButton login2;
    private javax.swing.JTabbedPane pane3;
    private javax.swing.JButton reset;
    private javax.swing.JButton sign2;
    private javax.swing.JPanel suru;
    private javax.swing.JPanel suruchi;
    private javax.swing.JTextField t6;
    private javax.swing.JPasswordField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JPasswordField t9;
    // End of variables declaration//GEN-END:variables
}
